In [1]:
from sklearn import datasets
import pandas as pd
import numpy as np

In [2]:
iris=datasets.load_iris()

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
iris=pd.DataFrame(data=np.c_[iris['data'],iris['target']],columns=iris['feature_names']+['target'])

In [7]:
species=[]
for i in range(len(iris['target'])):
    if iris['target'][i]==0:
        species.append('setosa')
    elif iris['target'][i]==1:
        species.append('versicolor')
    elif iris['target'][i]==2:
        species.append('verginica')
        

In [8]:
iris['species']=species

In [9]:
iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target    species  
0       0.0     setosa  
1       0.0     setosa  
2       0.0     setosa  
3       0.0     setosa  
4       0.0     setosa  
..      ...        ...  
145     2.0  verginica  
146     2.0  verginica  
147     2.0  verginica  
148     2.0  verginica  
149     2.0  verginica  

[150 rows x 6 columns]

In [10]:
from sklearn.model_selection import train_test_split
x=iris.drop(['target','species'],axis=1)
y=iris['target']

In [11]:
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [12]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: target, Length: 150, dtype: float64

In [13]:
x_train,x_valid_test,y_train,y_valid_test=train_test_split(x,y,test_size=0.3)

In [14]:
x_valid,x_test,y_valid,y_test=train_test_split(x_valid_test,y_valid_test,test_size=0.5)

In [15]:
print(len(x_train),len(x_valid),len(x_test))

105 22 23


In [16]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()

In [17]:
logmodel.fit(x_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [27]:
val=logmodel.predict(x_valid)

In [28]:
val

array([1., 0., 0., 2., 0., 0., 2., 2., 1., 2., 1., 1., 1., 1., 2., 1., 2.,
       1., 1., 1., 1., 0.])

In [29]:
valiid_prediction=logmodel.predict(x_valid)

In [30]:
valiid_prediction

array([1., 0., 0., 2., 0., 0., 2., 2., 1., 2., 1., 1., 1., 1., 2., 1., 2.,
       1., 1., 1., 1., 0.])

In [20]:
training_prediction=logmodel.predict(x_train)

In [21]:
training_prediction

array([2., 1., 0., 2., 2., 2., 1., 0., 2., 0., 2., 0., 1., 1., 2., 0., 0.,
       0., 1., 0., 0., 2., 0., 1., 2., 1., 2., 2., 2., 1., 2., 0., 1., 0.,
       2., 0., 1., 2., 1., 0., 0., 1., 2., 0., 1., 2., 2., 2., 0., 2., 1.,
       2., 1., 2., 1., 2., 0., 0., 0., 0., 2., 2., 2., 2., 0., 1., 0., 0.,
       2., 2., 1., 0., 1., 0., 1., 2., 2., 2., 2., 1., 2., 1., 0., 1., 1.,
       2., 1., 2., 0., 0., 0., 1., 2., 2., 1., 1., 2., 1., 0., 0., 2., 2.,
       0., 0., 2.])

In [22]:
testing_prediction=logmodel.predict(x_test)

In [23]:
testing_prediction

array([0., 2., 0., 0., 0., 0., 0., 1., 2., 0., 0., 1., 1., 0., 1., 1., 0.,
       0., 2., 1., 2., 2., 1.])

In [24]:
from sklearn.metrics import classification_report, confusion_matrix

In [34]:
#performance analysis for training data
print(classification_report(y_train,training_prediction))
#performance analysis for validation data
print(classification_report(y_valid,valiid_prediction))
#performance analysis for testing data
print(classification_report(y_test,testing_prediction))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        34
         1.0       1.00      0.94      0.97        31
         2.0       0.95      1.00      0.98        40

    accuracy                           0.98       105
   macro avg       0.98      0.98      0.98       105
weighted avg       0.98      0.98      0.98       105

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         5
         1.0       1.00      1.00      1.00        11
         2.0       1.00      1.00      1.00         6

    accuracy                           1.00        22
   macro avg       1.00      1.00      1.00        22
weighted avg       1.00      1.00      1.00        22

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        11
         1.0       1.00      0.88      0.93         8
         2.0       0.80      1.00      0.89         4

    accuracy        

In [36]:
#performance analysis for training data
print(confusion_matrix(y_train,training_prediction))
#performance analysis for validation data
print(confusion_matrix(y_valid,valiid_prediction))
#performance analysis for testing data
print(confusion_matrix(y_test,testing_prediction))

[[34  0  0]
 [ 0 29  2]
 [ 0  0 40]]
[[ 5  0  0]
 [ 0 11  0]
 [ 0  0  6]]
[[11  0  0]
 [ 0  7  1]
 [ 0  0  4]]
